### ISSUE TITLE
Error: Can't get track length on Deezer

### ISSUE THREAD

**Issue by cmonrroy88** [justinmdickey/goplaying#12]
I'm using Arch Linux and Deezer desktop (from de AUR) and I'm getting this error:

![imagen](https://github.com/user-attachments/assets/072f9e76-c0fa-4de0-819e-e5f63d4dd0e4)

but i see the metadata of current playing song in playerctl

![imagen](https://github.com/user-attachments/assets/99ecb536-dad4-431a-82ac-aef8a5da5136)

any idea of why its happens?  can i get logs from your app?

**Comment by justinmdickey** [comment]
Looks like 'playerctl metadata' can't get the song length either. So its likely an issue with Deezer, or playerctl.
